# Generated by Django 3.2.11 on 2022-06-15 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Graphe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('Barres horizontales', 'Barres horizontales'), ('Barres Verticales', 'Barres Verticales'), ('Lineaire', 'Lineaire'), ('Camembert', 'Camembert'), ('Beignet', 'Beignet')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Indicateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Intitule_Indicateur', models.CharField(max_length=100, unique=True)),
                ('Objectif', models.CharField(max_length=100)),
                ('Domaine', models.CharField(max_length=100)),
                ('Type', models.CharField(choices=[('IPP', 'Indicateurs de performance de productivité'), ('IPQ', 'Indicateurs de performance de qualité'), ('IPC', 'Indicateurs de performance de capacité'), ('IPS', 'Indicateurs de performance stratégiques')], max_length=50)),
                ('Methode_calcul', models.CharField(max_length=200)),
                ('Periodicite', models.CharField(choices=[('Annuelle', 'Annuelle'), ('Mensuelle', 'Mensuelle')], max_length=100)),
                ('validation_chef_dep', models.BooleanField(default=False)),
                ('validation_directeur', models.BooleanField(default=False)),
                ('graphe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.graphe')),
            ],
        ),
        migrations.CreateModel(
            name='TB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Intitule', models.CharField(max_length=200, unique=True)),
                ('Objectif', models.CharField(max_length=200)),
                ('validation_rapport', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Interpretation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contenu', models.TextField()),
                ('Date', models.DateField(auto_now_add=True)),
                ('validation_chef_dep', models.BooleanField(default=False)),
                ('validation_directeur', models.BooleanField(default=False)),
                ('indicateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.indicateur')),
            ],
        ),
        migrations.AddField(
            model_name='indicateur',
            name='tb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tb'),
        ),
        migrations.AddField(
            model_name='indicateur',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Donnee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Valeur', models.IntegerField()),
                ('indicateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.indicateur')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonneeMesure',
            fields=[
                ('donnee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.donnee')),
                ('mesure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.mesure')),
            ],
            bases=('home.donnee',),
        ),
        migrations.CreateModel(
            name='DonneeFilliale',
            fields=[
                ('donnee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.donnee')),
                ('filiale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.filiale')),
            ],
            bases=('home.donnee',),
        ),
        migrations.CreateModel(
            name='DonneeApplication',
            fields=[
                ('donnee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.donnee')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.application')),
            ],
            bases=('home.donnee',),
        ),
    ]
