# Generated by Django 3.2.11 on 2022-05-20 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphe',
            name='Nom',
        ),
        migrations.AddField(
            model_name='indicateur',
            name='Domaine',
            field=models.CharField(default='Sécurité des RH', max_length=100),
        ),
        migrations.AddField(
            model_name='indicateur',
            name='Methode_calcul',
            field=models.CharField(default='Nb utilisateur', max_length=200),
        ),
        migrations.AddField(
            model_name='indicateur',
            name='Objectif',
            field=models.CharField(default='objectif', max_length=100),
        ),
        migrations.AddField(
            model_name='indicateur',
            name='Source',
            field=models.CharField(default='DSSI', max_length=100),
        ),
        migrations.AddField(
            model_name='indicateur',
            name='Type',
            field=models.CharField(choices=[('IPP', 'Indicateurs de performance de productivité'), ('IPQ', 'Indicateurs de performance de qualité'), ('IPC', 'Indicateurs de performance de capacité'), ('IPS', 'Indicateurs de performance stratégiques')], default='IPS', max_length=50),
        ),
        migrations.AlterField(
            model_name='graphe',
            name='Type',
            field=models.CharField(choices=[('BH', 'Barres horizontales'), ('BV', 'Barres Verticales'), ('L', 'Lineaire'), ('C', 'Camembert'), ('B', 'Beignet')], max_length=50),
        ),
        migrations.AlterField(
            model_name='indicateur',
            name='Intitule_Indicateur',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='indicateur',
            name='Periodicite',
            field=models.CharField(choices=[('A', 'Annuelle'), ('T', 'Trimestrielle'), ('M', 'Mensuelle')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tb',
            name='Intitule',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='Interpretation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contenu', models.TextField()),
                ('Id_Indicateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.indicateur')),
            ],
        ),
    ]
