# Generated by Django 3.2.11 on 2022-06-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220615_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicateur',
            name='Source',
            field=models.CharField(default='DSSI', max_length=100),
        ),
        migrations.AddField(
            model_name='indicateur',
            name='type_donnees',
            field=models.CharField(choices=[('Mesure', 'Mesure'), ('Application', 'Application'), ('Filiale', 'Filiale'), ('Standard', 'Standard')], default='Standard', max_length=100),
        ),
        migrations.AlterField(
            model_name='indicateur',
            name='Domaine',
            field=models.CharField(default='Sécurité des RH', max_length=100),
        ),
        migrations.AlterField(
            model_name='indicateur',
            name='Methode_calcul',
            field=models.CharField(default='Nb utilisateur', max_length=200),
        ),
        migrations.AlterField(
            model_name='indicateur',
            name='Objectif',
            field=models.CharField(default='objectif', max_length=100),
        ),
        migrations.AlterField(
            model_name='indicateur',
            name='Type',
            field=models.CharField(choices=[('IPP', 'Indicateurs de performance de productivité'), ('IPQ', 'Indicateurs de performance de qualité'), ('IPC', 'Indicateurs de performance de capacité'), ('IPS', 'Indicateurs de performance stratégiques')], default='IPS', max_length=50),
        ),
    ]
