# Generated by Django 3.2.11 on 2022-05-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220528_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicateur',
            name='validation_chef_dep',
            field=models.BooleanField(default=False),
        ),
    ]
