# Generated by Django 3.2.11 on 2022-06-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_donnee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interpretation',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
