# Generated by Django 3.2.11 on 2022-06-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_donnee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb',
            name='validation_rapport',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='interpretation',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
