# Generated by Django 3.2.11 on 2022-05-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220520_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicateur',
            name='Periodicite',
            field=models.CharField(choices=[('Annuelle', 'Annuelle'), ('Trimestrielle', 'Trimestrielle'), ('Mensuelle', 'Mensuelle')], max_length=100),
        ),
    ]
