# Generated by Django 3.2.11 on 2022-05-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_indicateur_validation_chef_dep'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicateur',
            name='validation_directeur',
            field=models.BooleanField(default=False),
        ),
    ]
