# Generated by Django 3.2.11 on 2022-06-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_interpretation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb',
            name='validation_rapport',
            field=models.BooleanField(default=False),
        ),
    ]
