# Generated by Django 3.2.11 on 2022-05-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_indicateur_periodicite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphe',
            name='Type',
            field=models.CharField(choices=[('Barres horizontales', 'Barres horizontales'), ('Barres Verticales', 'Barres Verticales'), ('Lineaire', 'Lineaire'), ('Camembert', 'Camembert'), ('Beignet', 'Beignet')], max_length=50),
        ),
    ]
