# Generated by Django 3.2.11 on 2022-06-16 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220615_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicateur',
            name='Id_TB',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tb', verbose_name='tableau de bord'),
        ),
    ]
