# Generated by Django 3.2.11 on 2022-06-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220613_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donnee',
            name='validation_chef_dep',
        ),
        migrations.RemoveField(
            model_name='donnee',
            name='validation_directeur',
        ),
        migrations.AddField(
            model_name='interpretation',
            name='validation_chef_dep',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interpretation',
            name='validation_directeur',
            field=models.BooleanField(default=False),
        ),
    ]
