# Generated by Django 3.2.11 on 2022-06-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_donneeapplication_donneefilliale_donneemesure'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicateur',
            name='type_donnees',
            field=models.CharField(choices=[('Mesure', 'Mesure'), ('Application', 'Application'), ('Société', 'Société'), ('Standard', 'Standard')], default='Standard', max_length=100),
        ),
    ]
