# Generated by Django 3.2.11 on 2022-06-15 15:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_auto_20220614_1935'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_indicateur_type_donnees'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DonneeFilliale',
            new_name='DonneeFiliale',
        ),
        migrations.AlterField(
            model_name='indicateur',
            name='type_donnees',
            field=models.CharField(choices=[('Mesure', 'Mesure'), ('Application', 'Application'), ('Filiale', 'Filiale'), ('Standard', 'Standard')], default='Standard', max_length=100),
        ),
    ]
