# Generated by Django 3.2.11 on 2022-06-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20220616_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicateur',
            name='TypeMiniGraphe',
            field=models.CharField(choices=[('Lineaire', 'Lineaire'), ('Barres', 'Barres'), ('Camembert', 'Camembert'), ('Beignet', 'Beignet'), ('Radar', 'Radar')], default='Barres', max_length=100),
        ),
    ]
