# Generated by Django 3.2.11 on 2022-07-02 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_indicateur_typeminigraphe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicateur',
            name='Id_Graphe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.graphe', verbose_name='Graphe Bilan'),
        ),
        migrations.AlterField(
            model_name='indicateur',
            name='Id_TB',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tb', verbose_name='Tableau de bord'),
        ),
        migrations.AlterField(
            model_name='indicateur',
            name='TypeMiniGraphe',
            field=models.CharField(choices=[('Lineaire', 'Lineaire'), ('Barres', 'Barres'), ('Camembert', 'Camembert'), ('Beignet', 'Beignet'), ('Radar', 'Radar')], default='Barres', max_length=100, verbose_name='Type Mini Graphe'),
        ),
        migrations.AlterField(
            model_name='indicateur',
            name='type_donnees',
            field=models.CharField(choices=[('Mesure', 'Mesure'), ('Application', 'Application'), ('Filiale', 'Filiale'), ('Standard', 'Standard')], default='Standard', max_length=100, verbose_name='Type Données'),
        ),
    ]
