# Generated by Django 3.2.11 on 2022-05-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='poste',
            field=models.CharField(blank=True, choices=[('PDG', 'PDG'), ('Directeur', 'Directeur'), ('Chef département', 'Chef département'), ('Ingénieur', 'Ingénieur'), ('Admin', 'Admin')], max_length=50, null=True),
        ),
    ]
