# Generated by Django 3.2.11 on 2022-05-31 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_alter_customuser_poste'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='directions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.direction'),
        ),
        migrations.AddField(
            model_name='direction',
            name='filiales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.filiale'),
        ),
    ]
