# Generated by Django 3.2.11 on 2022-06-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_auto_20220531_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='poste',
            field=models.CharField(blank=True, choices=[('PDG', 'PDG'), ('Directeur', 'Directeur'), ('Chef département', 'Chef département'), ('Ingénieur', 'Ingénieur')], max_length=50, null=True),
        ),
    ]
