# Generated by Django 3.2.11 on 2022-06-09 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_departement_chef_dep'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sexe',
            field=models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin')], default='Masculin', max_length=10),
        ),
        migrations.AddField(
            model_name='filiale',
            name='pdg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
