# Generated by Django 3.2.11 on 2022-06-14 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_alter_customuser_sexe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_app', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Referentiel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_referentiel', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_mesure', models.CharField(max_length=20)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_domaine', models.CharField(max_length=20)),
                ('referentiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.referentiel')),
            ],
        ),
        migrations.AddField(
            model_name='categorie',
            name='domaine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.domaine'),
        ),
    ]
