# Generated by Django 3.2.11 on 2022-06-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_auto_20220614_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='nom_app',
            field=models.CharField(max_length=50),
        ),
    ]
